<?php

namespace App\Enums;

use App\Libs\Core\Enums\Enum;

class Countries extends Enum
{
    const AFRICA_DO_SUL = 1001;
    const AUSTRIA = 1002;
    const INDIA = 1003;
    const AFEGANISTAO = 1004;
    const ALBANIA = 1005;
    const ALEMANHA = 1006;
    const ANDORRA = 1007;
    const ANGOLA = 1008;
    const ANGUILA = 1009;
    const ANTARCTIDA = 10010;
    const ANTIGUA_E_BARBUDA = 10011;
    const ANTILHAS_NEERLANDESAS = 10012;
    const ARABIA_SAUDITA = 10013;
    const ARGELIA = 10014;
    const ARGENTINA = 10015;
    const ARMENIA = 10016;
    const ARUBA = 10017;
    const AUSTRALIA = 10018;
    const AZERBAIJAO = 10019;
    const BELGICA = 10020;
    const BOSNIA_E_HERZEGOVINA = 10021;
    const BAAMAS = 10022;
    const BANGLADECHE = 10023;
    const BAREM = 10024;
    const BARBADOS = 10025;
    const BELIZE = 10026;
    const BENIM = 10027;
    const BERMUDAS = 10028;
    const BIELORRUSSIA = 10029;
    const BIRMANIA = 10030;
    const BOLIVIA = 10031;
    const BOTSUANA = 10032;
    const BRASIL = 10033;
    const BRUNEI = 10034;
    const BULGARIA = 10035;
    const BURUNDI = 10036;
    const BURQUINA_FASO = 10037;
    const BUTAO = 10038;
    const CABO_VERDE = 10039;
    const CAMAROES = 10040;
    const CAMBOJA = 10041;
    const CANADA = 10042;
    const CATAR = 10043;
    const CAZAQUISTAO = 10044;
    const CHADE = 10045;
    const CHILE = 10046;
    const CHINA = 10047;
    const CHIPRE = 10048;
    const COLOMBIA = 10049;
    const COMORES = 10050;
    const CONGO_BRAZZAVILLE = 10051;
    const CONGO_KINSHASA = 10052;
    const COREIA_DO_NORTE = 10053;
    const COREIA_DO_SUL = 10054;
    const COSTA_RICA = 10055;
    const COSTA_DO_MARFIM = 10056;
    const CROACIA = 10057;
    const CUBA = 10058;
    const DINAMARCA = 10059;
    const DOMINICA = 10060;
    const EGIPTO = 10061;
    const EMIRATOS_ARABES_UNIDOS = 10062;
    const EQUADOR = 10063;
    const ERITREIA = 10064;
    const ESLOVAQUIA = 10065;
    const ESLOVENIA = 10066;
    const ESPANHA = 10067;
    const ESTONIA = 10068;
    const ESTADOS_UNIDOS = 10069;
    const ETIOPIA = 10070;
    const FAROE = 10071;
    const FIJI = 10072;
    const FILIPINAS = 10073;
    const FINLANDIA = 10074;
    const FRANCA = 10075;
    const GAMBIA = 10076;
    const GABAO = 10077;
    const GANA = 10078;
    const GEORGIA = 10079;
    const GEORGIA_DO_SUL_E_SANDWICH_DO_SUL = 10080;
    const GIBRALTAR = 10081;
    const GRECIA = 10082;
    const GRANADA = 10083;
    const GRONELANDIA = 10084;
    const GUADALUPE = 10085;
    const GUAME = 10086;
    const GUATEMALA = 10087;
    const GUIANA = 10088;
    const GUIANA_FRANCESA = 10089;
    const GUINE = 10090;
    const GUINE_EQUATORIAL = 10091;
    const GUINE_BISSAU = 10092;
    const HAITI = 10093;
    const HONDURAS = 10094;
    const HONG_KONG = 10095;
    const HUNGRIA = 10096;
    const IEMEN = 10097;
    const ILHA_BOUVET = 10098;
    const ILHA_NORFOLK = 10099;
    const ILHA_DO_NATAL = 100100;
    const ILHAS_CAIMAO = 100101;
    const ILHAS_COOK = 100102;
    const ILHAS_FALKLAND = 100103;
    const ILHAS_HEARD_E_MCDONALD = 100104;
    const ILHAS_MARSHALL = 100105;
    const ILHAS_MENORES_DISTANTES_DOS_ESTADOS_UNIDOS = 100106;
    const ILHAS_SALOMAO = 100107;
    const ILHAS_TURCAS_E_CAICOS = 100108;
    const ILHAS_VIRGENS_AMERICANAS = 100109;
    const ILHAS_VIRGENS_BRITANICAS = 100110;
    const ILHAS_DOS_COCOS = 100111;
    const INDONESIA = 100112;
    const IRAO = 100113;
    const IRAQUE = 100114;
    const IRLANDA = 100115;
    const ISLANDIA = 100116;
    const ISRAEL = 100117;
    const ITALIA = 100118;
    const JAMAICA = 100119;
    const JAPAO = 100120;
    const JIBUTI = 100121;
    const JORDANIA = 100122;
    const JUGOSLAVIA = 100123;
    const KUWAIT = 100124;
    const LIBANO = 100125;
    const LIBIA = 100126;
    const LAOS = 100127;
    const LESOTO = 100128;
    const LETONIA = 100129;
    const LIBERIA = 100130;
    const LISTENSTAINE = 100131;
    const LITUANIA = 100132;
    const LUXEMBURGO = 100133;
    const MEXICO = 100134;
    const MONACO = 100135;
    const MACAU = 100136;
    const MACEDONIA = 100137;
    const MADAGASCAR = 100138;
    const MALASIA = 100139;
    const MALAVI = 100140;
    const MALDIVAS = 100141;
    const MALI = 100142;
    const MALTA = 100143;
    const MARIANAS_DO_NORTE = 100144;
    const MARROCOS = 100145;
    const MARTINICA = 100146;
    const MAURICIA = 100147;
    const MAURITANIA = 100148;
    const MAYOTTE = 100149;
    const MICRONESIA = 100150;
    const MOCAMBIQUE = 100151;
    const MOLDAVIA = 100152;
    const MONGOLIA = 100153;
    const MONSERRATE = 100154;
    const NIGER = 100155;
    const NAMIBIA = 100156;
    const NAURU = 100157;
    const NEPAL = 100158;
    const NICARAGUA = 100159;
    const NIGERIA = 100160;
    const NIUE = 100161;
    const NORUEGA = 100162;
    const NOVA_CALEDONIA = 100163;
    const NOVA_ZELANDIA = 100164;
    const OMA = 100165;
    const PAISES_BAIXOS = 100166;
    const PALAU = 100167;
    const PANAMA = 100168;
    const PAPUA_NOVA_GUINE = 100169;
    const PAQUISTAO = 100170;
    const PARAGUAI = 100171;
    const PERU = 100172;
    const PITCAIRN = 100173;
    const POLONIA = 100174;
    const POLINESIA_FRANCESA = 100175;
    const PORTO_RICO = 100176;
    const PORTUGAL = 100177;
    const QUENIA = 100178;
    const QUIRGUIZISTAO = 100179;
    const QUIRIBATI = 100180;
    const RUSSIA = 100181;
    const REINO_UNIDO = 100182;
    const REPUBLICA_CENTRO_AFRICANA = 100183;
    const REPUBLICA_CHECA = 100184;
    const REPUBLICA_DOMINICANA = 100185;
    const REUNIAO = 100186;
    const ROMENIA = 100187;
    const RUANDA = 100188;
    const SAO_CRISTOVAO_E_NEVES = 100189;
    const SAO_MARINHO = 100190;
    const SAO_PEDRO_E_MIQUELON = 100191;
    const SAO_TOME_E_PRINCIPE = 100192;
    const SAO_VICENTE_E_GRANADINAS = 100193;
    const SIRIA = 100194;
    const SALVADOR = 100195;
    const SAMOA = 100196;
    const SAMOA_AMERICANA = 100197;
    const SANTA_HELENA = 100198;
    const SANTA_LUCIA = 100199;
    const SARA_OCIDENTAL = 100200;
    const SEICHELES = 100201;
    const SENEGAL = 100202;
    const SERRA_LEOA = 100203;
    const SINGAPURA = 100204;
    const SOMALIA = 100205;
    const SRI_LANCA = 100206;
    const SUECIA = 100207;
    const SUICA = 100208;
    const SUAZILANDIA = 100209;
    const SUDAO = 100210;
    const SURINAME = 100211;
    const SVALBARD_E_JAN_MAYEN = 100212;
    const TAILANDIA = 100213;
    const TAIWAN = 100214;
    const TAJIQUISTAO = 100215;
    const TANZANIA = 100216;
    const TERRITORIO_BRITANICO_DO_OCEANO_INDICO = 100217;
    const TERRITORIOS_AUSTRAIS_FRANCESES = 100218;
    const TIMOR_LESTE = 100219;
    const TOGO = 100220;
    const TOKELAU = 100221;
    const TONGA = 100222;
    const TRINDADE_E_TOBAGO = 100223;
    const TUNISIA = 100224;
    const TURQUEMENISTAO = 100225;
    const TURQUIA = 100226;
    const TUVALU = 100227;
    const UCRANIA = 100228;
    const UGANDA = 100229;
    const URUGUAI = 100230;
    const USBEQUISTAO = 100231;
    const VANUATU = 100232;
    const VATICANO = 100233;
    const VENEZUELA = 100234;
    const VIETNAME = 100235;
    const WALLIS_E_FUTUNA = 100236;
    const ZAMBIA = 100237;
    const ZIMBABUE = 100238;

    protected static array $enums = [
        self::AFRICA_DO_SUL                             => 'África do Sul',
        self::AUSTRIA                                   => 'Áustria',
        self::INDIA                                     => 'Índia',
        self::AFEGANISTAO                               => 'Afeganistão',
        self::ALBANIA                                   => 'Albânia',
        self::ALEMANHA                                  => 'Alemanha',
        self::ANDORRA                                   => 'Andorra',
        self::ANGOLA                                    => 'Angola',
        self::ANGUILA                                   => 'Anguila',
        self::ANTARCTIDA                                => 'Antárctida',
        self::ANTIGUA_E_BARBUDA                         => 'Antígua e Barbuda',
        self::ANTILHAS_NEERLANDESAS                     => 'Antilhas Neerlandesas',
        self::ARABIA_SAUDITA                            => 'Arábia Saudita',
        self::ARGELIA                                   => 'Argélia',
        self::ARGENTINA                                 => 'Argentina',
        self::ARMENIA                                   => 'Arménia',
        self::ARUBA                                     => 'Aruba',
        self::AUSTRALIA                                 => 'Austrália',
        self::AZERBAIJAO                                => 'Azerbaijão',
        self::BELGICA                                   => 'Bélgica',
        self::BOSNIA_E_HERZEGOVINA                      => 'Bósnia e Herzegovina',
        self::BAAMAS                                    => 'Baamas',
        self::BANGLADECHE                               => 'Bangladeche',
        self::BAREM                                     => 'Barém',
        self::BARBADOS                                  => 'Barbados',
        self::BELIZE                                    => 'Belize',
        self::BENIM                                     => 'Benim',
        self::BERMUDAS                                  => 'Bermudas',
        self::BIELORRUSSIA                              => 'Bielorrússia',
        self::BIRMANIA                                  => 'Birmânia',
        self::BOLIVIA                                   => 'Bolívia',
        self::BOTSUANA                                  => 'Botsuana',
        self::BRASIL                                    => 'Brasil',
        self::BRUNEI                                    => 'Brunei',
        self::BULGARIA                                  => 'Bulgária',
        self::BURUNDI                                   => 'Burúndi',
        self::BURQUINA_FASO                             => 'Burquina Faso',
        self::BUTAO                                     => 'Butão',
        self::CABO_VERDE                                => 'Cabo Verde',
        self::CAMAROES                                  => 'Camarões',
        self::CAMBOJA                                   => 'Camboja',
        self::CANADA                                    => 'Canadá',
        self::CATAR                                     => 'Catar',
        self::CAZAQUISTAO                               => 'Cazaquistão',
        self::CHADE                                     => 'Chade',
        self::CHILE                                     => 'Chile',
        self::CHINA                                     => 'China',
        self::CHIPRE                                    => 'Chipre',
        self::COLOMBIA                                  => 'Colômbia',
        self::COMORES                                   => 'Comores',
        self::CONGO_BRAZZAVILLE                         => 'Congo-Brazzaville',
        self::CONGO_KINSHASA                            => 'Congo-Kinshasa',
        self::COREIA_DO_NORTE                           => 'Coreia do Norte',
        self::COREIA_DO_SUL                             => 'Coreia do Sul',
        self::COSTA_RICA                                => 'Costa Rica',
        self::COSTA_DO_MARFIM                           => 'Costa do Marfim',
        self::CROACIA                                   => 'Croácia',
        self::CUBA                                      => 'Cuba',
        self::DINAMARCA                                 => 'Dinamarca',
        self::DOMINICA                                  => 'Domínica',
        self::EGIPTO                                    => 'Egipto',
        self::EMIRATOS_ARABES_UNIDOS                    => 'Emiratos Árabes Unidos',
        self::EQUADOR                                   => 'Equador',
        self::ERITREIA                                  => 'Eritreia',
        self::ESLOVAQUIA                                => 'Eslováquia',
        self::ESLOVENIA                                 => 'Eslovénia',
        self::ESPANHA                                   => 'Espanha',
        self::ESTONIA                                   => 'Estónia',
        self::ESTADOS_UNIDOS                            => 'Estados Unidos',
        self::ETIOPIA                                   => 'Etiópia',
        self::FAROE                                     => 'Faroé',
        self::FIJI                                      => 'Fiji',
        self::FILIPINAS                                 => 'Filipinas',
        self::FINLANDIA                                 => 'Finlândia',
        self::FRANCA                                    => 'França',
        self::GAMBIA                                    => 'Gâmbia',
        self::GABAO                                     => 'Gabão',
        self::GANA                                      => 'Gana',
        self::GEORGIA                                   => 'Geórgia',
        self::GEORGIA_DO_SUL_E_SANDWICH_DO_SUL          => 'Geórgia do Sul e Sandwich do Sul',
        self::GIBRALTAR                                 => 'Gibraltar',
        self::GRECIA                                    => 'Grécia',
        self::GRANADA                                   => 'Granada',
        self::GRONELANDIA                               => 'Gronelândia',
        self::GUADALUPE                                 => 'Guadalupe',
        self::GUAME                                     => 'Guame',
        self::GUATEMALA                                 => 'Guatemala',
        self::GUIANA                                    => 'Guiana',
        self::GUIANA_FRANCESA                           => 'Guiana Francesa',
        self::GUINE                                     => 'Guiné',
        self::GUINE_EQUATORIAL                          => 'Guiné Equatorial',
        self::GUINE_BISSAU                              => 'Guiné-Bissau',
        self::HAITI                                     => 'Haiti',
        self::HONDURAS                                  => 'Honduras',
        self::HONG_KONG                                 => 'Hong Kong',
        self::HUNGRIA                                   => 'Hungria',
        self::IEMEN                                     => 'Iémen',
        self::ILHA_BOUVET                               => 'Ilha Bouvet',
        self::ILHA_NORFOLK                              => 'Ilha Norfolk',
        self::ILHA_DO_NATAL                             => 'Ilha do Natal',
        self::ILHAS_CAIMAO                              => 'Ilhas Caimão',
        self::ILHAS_COOK                                => 'Ilhas Cook',
        self::ILHAS_FALKLAND                            => 'Ilhas Falkland',
        self::ILHAS_HEARD_E_MCDONALD                    => 'Ilhas Heard e McDonald',
        self::ILHAS_MARSHALL                            => 'Ilhas Marshall',
        self::ILHAS_MENORES_DISTANTES_DOS_ESTADOS_UNIDOS=> 'Ilhas Menores Distantes dos Estados Unidos',
        self::ILHAS_SALOMAO                             => 'Ilhas Salomão',
        self::ILHAS_TURCAS_E_CAICOS                     => 'Ilhas Turcas e Caicos',
        self::ILHAS_VIRGENS_AMERICANAS                  => 'Ilhas Virgens Americanas',
        self::ILHAS_VIRGENS_BRITANICAS                  => 'Ilhas Virgens Britânicas',
        self::ILHAS_DOS_COCOS                           => 'Ilhas dos Cocos',
        self::INDONESIA                                 => 'Indonésia',
        self::IRAO                                      => 'Irão',
        self::IRAQUE                                    => 'Iraque',
        self::IRLANDA                                   => 'Irlanda',
        self::ISLANDIA                                  => 'Islândia',
        self::ISRAEL                                    => 'Israel',
        self::ITALIA                                    => 'Itália',
        self::JAMAICA                                   => 'Jamaica',
        self::JAPAO                                     => 'Japão',
        self::JIBUTI                                    => 'Jibuti',
        self::JORDANIA                                  => 'Jordânia',
        self::JUGOSLAVIA                                => 'Jugoslávia',
        self::KUWAIT                                    => 'Kuwait',
        self::LIBANO                                    => 'Líbano',
        self::LIBIA                                     => 'Líbia',
        self::LAOS                                      => 'Laos',
        self::LESOTO                                    => 'Lesoto',
        self::LETONIA                                   => 'Letónia',
        self::LIBERIA                                   => 'Libéria',
        self::LISTENSTAINE                              => 'Listenstaine',
        self::LITUANIA                                  => 'Lituânia',
        self::LUXEMBURGO                                => 'Luxemburgo',
        self::MEXICO                                    => 'México',
        self::MONACO                                    => 'Mónaco',
        self::MACAU                                     => 'Macau',
        self::MACEDONIA                                 => 'Macedónia',
        self::MADAGASCAR                                => 'Madagáscar',
        self::MALASIA                                   => 'Malásia',
        self::MALAVI                                    => 'Malávi',
        self::MALDIVAS                                  => 'Maldivas',
        self::MALI                                      => 'Mali',
        self::MALTA                                     => 'Malta',
        self::MARIANAS_DO_NORTE                         => 'Marianas do Norte',
        self::MARROCOS                                  => 'Marrocos',
        self::MARTINICA                                 => 'Martinica',
        self::MAURICIA                                  => 'Maurícia',
        self::MAURITANIA                                => 'Mauritânia',
        self::MAYOTTE                                   => 'Mayotte',
        self::MICRONESIA                                => 'Micronésia',
        self::MOCAMBIQUE                                => 'Moçambique',
        self::MOLDAVIA                                  => 'Moldávia',
        self::MONGOLIA                                  => 'Mongólia',
        self::MONSERRATE                                => 'Monserrate',
        self::NIGER                                     => 'Níger',
        self::NAMIBIA                                   => 'Namíbia',
        self::NAURU                                     => 'Nauru',
        self::NEPAL                                     => 'Nepal',
        self::NICARAGUA                                 => 'Nicarágua',
        self::NIGERIA                                   => 'Nigéria',
        self::NIUE                                      => 'Niue',
        self::NORUEGA                                   => 'Noruega',
        self::NOVA_CALEDONIA                            => 'Nova Caledónia',
        self::NOVA_ZELANDIA                             => 'Nova Zelândia',
        self::OMA                                       => 'Omã',
        self::PAISES_BAIXOS                             => 'Países Baixos',
        self::PALAU                                     => 'Palau',
        self::PANAMA                                    => 'Panamá',
        self::PAPUA_NOVA_GUINE                          => 'Papua-Nova Guiné',
        self::PAQUISTAO                                 => 'Paquistão',
        self::PARAGUAI                                  => 'Paraguai',
        self::PERU                                      => 'Peru',
        self::PITCAIRN                                  => 'Pitcairn',
        self::POLONIA                                   => 'Polónia',
        self::POLINESIA_FRANCESA                        => 'Polinésia Francesa',
        self::PORTO_RICO                                => 'Porto Rico',
        self::PORTUGAL                                  => 'Portugal',
        self::QUENIA                                    => 'Quénia',
        self::QUIRGUIZISTAO                             => 'Quirguizistão',
        self::QUIRIBATI                                 => 'Quiribáti',
        self::RUSSIA                                    => 'Rússia',
        self::REINO_UNIDO                               => 'Reino Unido',
        self::REPUBLICA_CENTRO_AFRICANA                 => 'República Centro-Africana',
        self::REPUBLICA_CHECA                           => 'República Checa',
        self::REPUBLICA_DOMINICANA                      => 'República Dominicana',
        self::REUNIAO                                   => 'Reunião',
        self::ROMENIA                                   => 'Roménia',
        self::RUANDA                                    => 'Ruanda',
        self::SAO_CRISTOVAO_E_NEVES                     => 'São Cristóvão e Neves',
        self::SAO_MARINHO                               => 'São Marinho',
        self::SAO_PEDRO_E_MIQUELON                      => 'São Pedro e Miquelon',
        self::SAO_TOME_E_PRINCIPE                       => 'São Tomé e Príncipe',
        self::SAO_VICENTE_E_GRANADINAS                  => 'São Vicente e Granadinas',
        self::SIRIA                                     => 'Síria',
        self::SALVADOR                                  => 'Salvador',
        self::SAMOA                                     => 'Samoa',
        self::SAMOA_AMERICANA                           => 'Samoa Americana',
        self::SANTA_HELENA                              => 'Santa Helena',
        self::SANTA_LUCIA                               => 'Santa Lúcia',
        self::SARA_OCIDENTAL                            => 'Sara Ocidental',
        self::SEICHELES                                 => 'Seicheles',
        self::SENEGAL                                   => 'Senegal',
        self::SERRA_LEOA                                => 'Serra Leoa',
        self::SINGAPURA                                 => 'Singapura',
        self::SOMALIA                                   => 'Somália',
        self::SRI_LANCA                                 => 'Sri Lanca',
        self::SUECIA                                    => 'Suécia',
        self::SUICA                                     => 'Suíça',
        self::SUAZILANDIA                               => 'Suazilândia',
        self::SUDAO                                     => 'Sudão',
        self::SURINAME                                  => 'Suriname',
        self::SVALBARD_E_JAN_MAYEN                      => 'Svalbard e Jan Mayen',
        self::TAILANDIA                                 => 'Tailândia',
        self::TAIWAN                                    => 'Taiwan',
        self::TAJIQUISTAO                               => 'Tajiquistão',
        self::TANZANIA                                  => 'Tanzânia',
        self::TERRITORIO_BRITANICO_DO_OCEANO_INDICO     => 'Território Britânico do Oceano Índico',
        self::TERRITORIOS_AUSTRAIS_FRANCESES            => 'Territórios Austrais Franceses',
        self::TIMOR_LESTE                               => 'Timor Leste',
        self::TOGO                                      => 'Togo',
        self::TOKELAU                                   => 'Tokelau',
        self::TONGA                                     => 'Tonga',
        self::TRINDADE_E_TOBAGO                         => 'Trindade e Tobago',
        self::TUNISIA                                   => 'Tunísia',
        self::TURQUEMENISTAO                            => 'Turquemenistão',
        self::TURQUIA                                   => 'Turquia',
        self::TUVALU                                    => 'Tuvalu',
        self::UCRANIA                                   => 'Ucrânia',
        self::UGANDA                                    => 'Uganda',
        self::URUGUAI                                   => 'Uruguai',
        self::USBEQUISTAO                               => 'Usbequistão',
        self::VANUATU                                   => 'Vanuatu',
        self::VATICANO                                  => 'Vaticano',
        self::VENEZUELA                                 => 'Venezuela',
        self::VIETNAME                                  => 'Vietname',
        self::WALLIS_E_FUTUNA                           => 'Wallis e Futuna',
        self::ZAMBIA                                    => 'Zâmbia',
        self::ZIMBABUE                                  => 'Zimbábue',
    ];
}
